description "ScrapCoin Core Daemon"

start on runlevel [2345]
stop on starting rc RUNLEVEL=[016]

env SCRAPCOIND_BIN="/usr/bin/scrapcoind"
env SCRAPCOIND_USER="scrapcoin"
env SCRAPCOIND_GROUP="scrapcoin"
env SCRAPCOIND_PIDDIR="/var/run/scrapcoind"
# upstart can't handle variables constructed with other variables
env SCRAPCOIND_PIDFILE="/var/run/scrapcoind/scrapcoind.pid"
env SCRAPCOIND_CONFIGFILE="/etc/scrapcoin/scrapcoin.conf"
env SCRAPCOIND_DATADIR="/var/lib/scrapcoind"

expect fork

respawn
respawn limit 5 120
kill timeout 60

pre-start script
    # this will catch non-existent config files
    # scrapcoind will check and exit with this very warning, but it can do so
    # long after forking, leaving upstart to think everything started fine.
    # since this is a commonly encountered case on install, just check and
    # warn here.
    if ! grep -qs '^rpcpassword=' "$SCRAPCOIND_CONFIGFILE" ; then
        echo "ERROR: You must set a secure rpcpassword to run scrapcoind."
        echo "The setting must appear in $SCRAPCOIND_CONFIGFILE"
        echo
        echo "This password is security critical to securing wallets "
        echo "and must not be the same as the rpcuser setting."
        echo "You can generate a suitable random password using the following"
        echo "command from the shell:"
        echo
        echo "bash -c 'tr -dc a-zA-Z0-9 < /dev/urandom | head -c32 && echo'"
        echo
        echo "It is also recommended that you also set alertnotify so you are "
        echo "notified of problems:"
        echo
        echo "ie: alertnotify=echo %%s | mail -s \"ScrapCoin Alert\"" \
            "admin@foo.com"
        echo
        exit 1
    fi

    mkdir -p "$SCRAPCOIND_PIDDIR"
    chmod 0755 "$SCRAPCOIND_PIDDIR"
    chown $SCRAPCOIND_USER:$SCRAPCOIND_GROUP "$SCRAPCOIND_PIDDIR"
    chown $SCRAPCOIND_USER:$SCRAPCOIND_GROUP "$SCRAPCOIND_CONFIGFILE"
    chmod 0660 "$SCRAPCOIND_CONFIGFILE"
end script

exec start-stop-daemon \
    --start \
    --pidfile "$SCRAPCOIND_PIDFILE" \
    --chuid $SCRAPCOIND_USER:$SCRAPCOIND_GROUP \
    --exec "$SCRAPCOIND_BIN" \
    -- \
    -pid="$SCRAPCOIND_PIDFILE" \
    -conf="$SCRAPCOIND_CONFIGFILE" \
    -datadir="$SCRAPCOIND_DATADIR" \
    -disablewallet \
    -daemon

