name: pepecoin-core
# Running 'snapcraft register <name>' is advised
version: '1.14.6'
summary: Reference client of Pepecoin, a peer-to-peer digital currency like Bitcoin.
description: |
  Pepecoin is a community-driven cryptocurrency that was inspired by Dogecoin. The Pepecoin Core software allows anyone to operate a node in the Pepecoin blockchain networks and uses the Scrypt hashing method for Proof of Work. It is adapted from Bitcoin Core and other cryptocurrencies.

grade: stable
confinement: strict
base: core18
compression: lzo
architectures:
  - build-on: amd64
    run-on: amd64
  - build-on: arm64
    run-on: arm64
  - build-on: i386
    run-on: i386

apps:
  d:
    command: pepecoind
    plugs: [home, removable-media, network, network-bind]
    environment:
      # Override HOME so the datadir is located at ~/snap/pepecoin-core/common/.pepecoin/ instead of ~/snap/pepecoin-core/current/.pepecoin/, and each new version of the snap won't have a different data directory: https://docs.snapcraft.io/environment-variables/7983
      HOME: $SNAP_USER_COMMON
  qt:
    command: desktop-launch pepecoin-qt
    plugs: [home, removable-media, network, network-bind, desktop, x11, unity7]
    environment:
      HOME: $SNAP_USER_COMMON
      DISABLE_WAYLAND: 1
  cli:
    command: pepecoin-cli
    plugs: [home, removable-media, network]
    environment:
      HOME: $SNAP_USER_COMMON
  tx:
    command: pepecoin-tx
    plugs: [home, removable-media, network]
    environment:
      HOME: $SNAP_USER_COMMON
  test:
    command: test_pepecoin
    plugs: [home, removable-media, network]
    environment:
      HOME: $SNAP_USER_COMMON

parts:
  desktop-qt5:
    # So desktop-launch from qt5 is udsable
    # Adapted from https://github.com/ubuntu/snapcraft-desktop-helpers/blob/master/snapcraft.yaml
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-depth: 1
    source-subdir: qt
    source-commit: ec861254c2a1d2447b2c589446e6cdf04c75c260
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - build-essential
      - qtbase5-dev
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - try: [appmenu-qt5] # not available on core18
      - locales-all
      - xdg-user-dirs
      - fcitx-frontend-qt5

  pepecoin-core:
    plugin: nil
    override-build: |
      echo "This script is viewable at https://github.com/pepecoinppc/pepecoin/blob/master/contrib/snap/snapcraft.yaml"
      echo "Downloading files..."
      if [ "$SNAPCRAFT_ARCH_TRIPLET" = "i386-linux-gnu" ]; then # snap designates 32-bit as i386, but pepecoin designates it as i686
        BUILD_ARCH_TRIPLET=i686-pc-linux-gnu
      else
        BUILD_ARCH_TRIPLET=$SNAPCRAFT_ARCH_TRIPLET
      fi
      wget https://github.com/pepecoinppc/pepecoin/releases/download/v${SNAPCRAFT_PROJECT_VERSION}/pepecoin-${SNAPCRAFT_PROJECT_VERSION}-${BUILD_ARCH_TRIPLET}.tar.gz
      wget https://github.com/pepecoinppc/gitian.sigs/archive/refs/heads/master.tar.gz
      tar -xvf master.tar.gz
      echo "Verifying secure hash matches signed values..."
      checksum=$(sha256sum pepecoin-${SNAPCRAFT_PROJECT_VERSION}-${BUILD_ARCH_TRIPLET}.tar.gz)
      if ! (grep -r $checksum * | grep pepecoin-${SNAPCRAFT_PROJECT_VERSION}-${BUILD_ARCH_TRIPLET}.tar.gz); then
        echo "Secure hash not verified."
        return
      else
        echo "Secure hash verified."
      fi
      tar -xvf pepecoin-${SNAPCRAFT_PROJECT_VERSION}-${BUILD_ARCH_TRIPLET}.tar.gz
      echo "Running tests..."
      if ! (pepecoin-${SNAPCRAFT_PROJECT_VERSION}/bin/test_pepecoin); then
        echo "Pepecoin tests failed."
        return
      else
        echo "Pepecoin tests passed."
      fi
      wget https://raw.githubusercontent.com/pepecoinppc/pepecoin/v${SNAPCRAFT_PROJECT_VERSION}/doc/release-notes.md
      cat release-notes.md
      echo "Installing Pepecoin Core..."
      echo "Version ${SNAPCRAFT_PROJECT_VERSION}"
      install -m 0755 -D -t $SNAPCRAFT_PART_INSTALL/bin pepecoin-${SNAPCRAFT_PROJECT_VERSION}/bin/pepecoind
      if ! ([ "$BUILD_ARCH_TRIPLET" = "aarch64-linux-gnu" ]); then # there is no official pepecoin-qt build on arm64
        install -m 0755 -D -t $SNAPCRAFT_PART_INSTALL/bin pepecoin-${SNAPCRAFT_PROJECT_VERSION}/bin/pepecoin-qt
      fi
      install -m 0755 -D -t $SNAPCRAFT_PART_INSTALL/bin pepecoin-${SNAPCRAFT_PROJECT_VERSION}/bin/pepecoin-cli
      install -m 0755 -D -t $SNAPCRAFT_PART_INSTALL/bin pepecoin-${SNAPCRAFT_PROJECT_VERSION}/bin/pepecoin-tx
      install -m 0755 -D -t $SNAPCRAFT_PART_INSTALL/bin pepecoin-${SNAPCRAFT_PROJECT_VERSION}/bin/test_pepecoin
      wget https://raw.githubusercontent.com/pepecoinppc/pepecoin/master/share/pixmaps/pepecoin128.png
      install -m 0644 -D -t $SNAPCRAFT_PART_INSTALL/share/pixmaps pepecoin128.png
    build-packages:
      - wget
    after:
      - desktop-qt5
